services:
    opale.kernel.listener.command_dispatch:
        class: Opale\ConsoleExceptionBundle\Listener\ConsoleExceptionListener
        arguments:
            - "@logger"
        deprecated: 'The "%service_id%" service is deprecated and useless starting with Symfony 3.3'
        tags:
            - { name: kernel.event_listener, event: console.exception }
